const lessonTitle = "无边的回忆";

const lessonData = [
    // ===== 第1段 =====
    ["我", "wǒ", "I", "Saya"],
    ["有", "yǒu", "have", "mempunyai"],
    ["一双", "yì shuāng", "a pair of", "sepasang"],
    ["塑料", "sù liào", "plastic", "plastik"],
    ["的", "de", "", ""],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["，", "", "", ""],
    ["是", "shì", "was", "ialah"],
    ["在", "zài", "at", "pada"],
    ["出国前", "chū guó qián", "before going abroad", "sebelum ke luar negara"],
    ["两年", "liǎng nián", "two years", "dua tahun"],
    ["买的", "mǎi de", "bought", "dibeli"],
    ["，", "", "", ""],
    ["出国后", "chū guó hòu", "after going abroad", "selepas ke luar negara"],
    ["又", "yòu", "again", "lagi"],
    ["穿了", "chuān le", "wore", "memakai"],
    ["五年", "wǔ nián", "five years", "lima tahun"],
    ["。", "", "", ""],
    ["它的", "tā de", "Its", "Ia punya"],
    ["形状", "xíng zhuàng", "shape", "bentuk"],
    ["很普通", "hěn pǔ tōng", "very ordinary", "sangat biasa"],
    ["，", "", "", ""],
    ["就像", "jiù xiàng", "just like", "seperti"],
    ["你在", "nǐ zài", "you in", "awak di"],
    ["台北街头", "tái běi jiē tóu", "Taipei streets", "jalan Taipei"],
    ["随处可见", "suí chù kě jiàn", "can be seen everywhere", "boleh dilihat di merata tempat"],
    ["的", "de", "", ""],
    ["最平常", "zuì píng cháng", "most ordinary", "paling biasa"],
    ["的样式", "de yàng shì", "style", "gaya"],
    ["：", "", "", ""],
    ["平底", "píng dǐ", "flat sole", "tapak rata"],
    ["，", "", "", ""],
    ["浅蓝色", "qiǎn lán sè", "light blue", "biru muda"],
    ["，", "", "", ""],
    ["前端", "qián duān", "front end", "hujung depan"],
    ["镂空", "lòu kōng", "hollowed out", "berlubang"],
    ["成", "chéng", "into", "menjadi"],
    ["六条", "liù tiáo", "six", "enam"],
    ["圆带子", "yuán dài zi", "round straps", "tali bulat"],
    ["，", "", "", ""],
    ["中间", "zhōng jiān", "in the middle", "di tengah"],
    ["用一个结", "yòng yí ge jié", "using a knot", "menggunakan simpulan"],
    ["把它们", "bǎ tā men", "to connect them", "menyatukannya"],
    ["连起来", "lián qǐ lái", "together", "menghubungkan"],
    ["。", "", "", ""],
    ["买的", "mǎi de", "When buying", "Semasa membeli"],
    ["时候", "shí hou", "", ""],
    ["，", "", "", ""],
    ["是", "shì", "it was", "ialah"],
    ["喜欢", "xǐ huān", "liked", "suka"],
    ["它的", "tā de", "its", "ia punya"],
    ["颜色", "yán sè", "colour", "warna"],
    ["。", "", "", ""],
    ["穿了", "chuān le", "After wearing", "Selepas memakai"],
    ["五六年后", "wǔ liù nián hòu", "five or six years later", "lima enam tahun kemudian"],
    ["，", "", "", ""],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["由", "yóu", "from", "daripada"],
    ["浅蓝", "qiǎn lán", "light blue", "biru muda"],
    ["变成", "biàn chéng", "changed to", "berubah menjadi"],
    ["浅灰", "qiǎn huī", "light grey", "kelabu muda"],
    ["，", "", "", ""],
    ["鞋底", "xié dǐ", "soles", "tapak kasut"],
    ["也", "yě", "also", "juga"],
    ["磨得", "mó de", "worn", "haus"],
    ["一边高", "yì biān gāo", "one side higher", "sebelah tinggi"],
    ["一边低了", "yì biān dī le", "one side lower", "sebelah rendah"],
    ["。", "", "", ""],
    ["好几次", "hǎo jǐ cì", "Many times", "Beberapa kali"],
    ["，", "", "", ""],
    ["有", "yǒu", "there were", "ada"],
    ["爱管闲事的", "ài guǎn xián shì de", "nosy", "suka masuk campur"],
    ["，", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["好心的", "hǎo xīn de", "kind-hearted", "baik hati"],
    ["女孩子", "nǚ hái zi", "girls", "gadis-gadis"],
    ["劝我", "quàn wǒ", "advised me", "menasihati saya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["阿蓉", "ā róng", "A Rong", "A Rong"],
    ["，", "", "", ""],
    ["你这双", "nǐ zhè shuāng", "your", "awak punya"],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["太老爷了", "tài lǎo ye le", "too old-fashioned", "terlalu ketinggalan zaman"],
    ["。”", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["阿蓉", "ā róng", "A Rong", "A Rong"],
    ["你该", "nǐ gāi", "you should", "awak patut"],
    ["换拖鞋啦", "huàn tuō xié la", "change your slippers", "tukar selipar"],
    ["！”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["总是", "zǒng shì", "always", "selalu"],
    ["微笑地", "wēi xiào de", "smilingly", "sambil tersenyum"],
    ["回答", "huí dá", "reply", "menjawab"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["还可以穿嘛", "hái kě yǐ chuān ma", "I can still wear them", "Masih boleh pakai"],
    ["，", "", "", ""],
    ["我很喜欢它", "wǒ hěn xǐ huān tā", "I like them very much", "Saya sangat sukakannya"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["如果", "rú guǒ", "If", "Jika"],
    ["我的回答", "wǒ de huí dá", "my answer", "jawapan saya"],
    ["换来", "huàn lái", "would bring", "mendapat"],
    ["的是", "de shì", "", ""],
    ["一个", "yí gè", "a", "sebuah"],
    ["很不以为然", "hěn bù yǐ rán", "disapproving", "tidak bersetuju"],
    ["的表情", "de biǎo qíng", "expression", "ekspresi"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["就会", "jiù huì", "would", "akan"],
    ["设法", "shè fǎ", "try to", "cuba"],
    ["转变", "zhuǎn biàn", "change", "menukar"],
    ["一个话题", "yí gè huà tí", "the topic", "topik"],
    ["。", "", "", ""],
    ["如果", "rú guǒ", "If", "Jika"],
    ["对方", "duì fāng", "the other person", "orang itu"],
    ["还会", "hái huì", "would still", "masih akan"],
    ["对我", "duì wǒ", "to me", "kepada saya"],
    ["善意地", "shàn yì de", "kindly", "dengan baik"],
    ["摇摇头", "yáo yáo tóu", "shake head", "geleng kepala"],
    ["，", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["笑一笑", "xiào yí xiào", "smile", "senyum"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["就", "jiù", "then", "lalu"],
    ["会", "huì", "would", "akan"],
    ["忍不住", "rěn bù zhù", "couldn't help", "tidak tahan"],
    ["告诉她", "gào su tā", "tell her", "memberitahu dia"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你知道", "nǐ zhī dào", "Do you know", "Awak tahu"],
    ["我", "wǒ", "why I", "saya"],
    ["为什么", "wèi shén me", "", ""],
    ["舍不得丢", "shě bu de diū", "can't bear to throw away", "sayang nak buang"],
    ["它的原因吗", "tā de yuán yīn ma", "this pair", "sebabnya"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["而", "ér", "And", "Dan"],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["个", "gè", "a", "satu"],
    ["让生命", "ràng shēng mìng", "that makes life", "membuatkan kehidupan"],
    ["在刹那间", "zài chà nà jiān", "in an instant", "dalam sekelip mata"],
    ["变得", "biàn de", "become", "menjadi"],
    ["非常温柔的回忆", "fēi cháng wēn róu de huí yì", "very gentle memory", "kenangan yang sangat lembut"],
    ["。", "", "", ""],
    ["大学快毕业时", "dà xué kuài bì yè shí", "When I was about to graduate", "Semasa hampir tamat universiti"],
    ["，", "", "", ""],
    ["课比较少", "kè bǐ jiào shǎo", "fewer classes", "kelas kurang"],
    ["，", "", "", ""],
    ["家住在", "jiā zhù zài", "home was at", "rumah terletak di"],
    ["北投山上", "běi tóu shān shàng", "Beitou mountain", "gunung Beitou"],
    ["，", "", "", ""],
    ["没有课的早上", "méi yǒu kè de zǎo shàng", "on mornings without class", "pada pagi tanpa kelas"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["常常会", "cháng cháng huì", "often would", "sering akan"],
    ["带着", "dài zhe", "take", "membawa"],
    ["两只小狗", "liǎng zhī xiǎo gǒu", "two puppies", "dua ekor anak anjing"],
    ["满山乱跑", "mǎn shān luàn pǎo", "run wildly on the mountain", "berlari-lari di gunung"],
    ["。", "", "", ""],
    ["有太阳的日子", "yǒu tài yáng de rì zi", "On sunny days", "Pada hari yang cerah"],
    ["，", "", "", ""],
    ["大屯山腰上的", "dà tún shān yāo shàng de", "on the mountainside of Datun", "di lereng Gunung Datun"],
    ["美丽", "měi lì", "beauty", "keindahan"],
    ["简直", "jiǎn zhí", "simply", "sungguh"],
    ["无法形容", "wú fǎ xíng róng", "indescribable", "tidak dapat digambarkan"],
    ["。", "", "", ""],
    ["有时候", "yǒu shí hou", "Sometimes", "Kadang-kadang"],
    ["我", "wǒ", "I", "Saya"],
    ["可以", "kě yǐ", "could", "boleh"],
    ["一直", "yì zhí", "continue", "terus"],
    ["走下去", "zǒu xià qù", "walk on", "berjalan"],
    ["，", "", "", ""],
    ["走上", "zǒu shàng", "walk", "berjalan"],
    ["一两个钟头", "yì liǎng gè zhōng tóu", "one or two hours", "satu dua jam"],
    ["的路", "de lù", "", ""],
    ["，", "", "", ""],
    ["最让我快乐的", "zuì ràng wǒ kuài lè de", "what made me happiest", "yang paling menggembirakan saya"],
    ["是", "shì", "was", "ialah"],
    ["在行走中", "zài xíng zǒu zhōng", "while walking", "semasa berjalan"],
    ["猛然回过头", "měng rán huí guò tóu", "suddenly turn back", "tiba-tiba menoleh"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["再仔细辨认", "zài zǐ xì biàn rèn", "then carefully identify", "kemudian perhatikan dengan teliti"],
    ["，", "", "", ""],
    ["山坡下面", "shān pō xià miàn", "below the hillside", "di bawah lereng"],
    ["，", "", "", ""],
    ["哪一幢", "nǎ yī zhuàng", "which one", "yang mana"],
    ["是", "shì", "is", "ialah"],
    ["我的家", "wǒ de jiā", "my home", "rumah saya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["走着走着", "zǒu zhe zǒu zhe", "Walking and walking", "Semasa berjalan"],
    ["，", "", "", ""],
    ["我的", "wǒ de", "my", "saya punya"],
    ["新拖鞋", "xīn tuō xié", "new slippers", "selipar baru"],
    ["就", "jiù", "then", "lalu"],
    ["不像样了", "bù xiàng yàng le", "became worn out", "tidak seperti rupa asal"],
    ["。", "", "", ""],
    ["不过", "bú guò", "However", "Tetapi"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["没时间", "méi shí jiān", "had no time", "tiada masa"],
    ["管它", "guǎn tā", "to care for them", "untuk mengambil berat"],
    ["，", "", "", ""],
    ["我的下午", "wǒ de xià wǔ", "my afternoons", "petang saya"],
    ["都是", "dōu shì", "were all", "semuanya"],
    ["排得满满", "pái de mǎn mǎn", "fully scheduled", "padat dengan jadual"],
    ["，", "", "", ""],
    ["别有用处的", "bié yǒu yòng chù de", "with other purposes", "untuk tujuan lain"],
    ["。", "", "", ""],
    ["晚上", "wǎn shàng", "At night", "Pada waktu malam"],
    ["回家后", "huí jiā hòu", "after returning home", "selepas pulang"],
    ["赶快", "gǎn kuài", "quickly", "cepat"],
    ["洗个澡", "xǐ ge zǎo", "take a shower", "mandi"],
    ["就睡了", "jiù shuì le", "and went to bed", "dan terus tidur"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["一天傍晚", "yì tiān bàng wǎn", "One evening", "Suatu petang"],
    ["，", "", "", ""],
    ["放学回家", "fàng xué huí jiā", "returning from school", "pulang dari sekolah"],
    ["，", "", "", ""],
    ["隔着", "gé zhe", "across", "merentasi"],
    ["矮矮的", "ǎi ǎi de", "low", "rendah"],
    ["石墙", "shí qiáng", "stone wall", "tembok batu"],
    ["，", "", "", ""],
    ["看见", "kàn jiàn", "saw", "melihat"],
    ["我的拖鞋", "wǒ de tuō xié", "my slippers", "selipar saya"],
    ["被", "bèi", "were", "telah"],
    ["整整齐齐地", "zhěng zhěng qí qí de", "neatly", "dengan kemas"],
    ["摆在", "bǎi zài", "placed on", "diletakkan di"],
    ["花园里", "huā yuán lǐ", "the garden", "taman"],
    ["的", "de", "", ""],
    ["水泥小路", "shuǐ ní xiǎo lù", "cement path", "jalan simen"],
    ["上", "shàng", "", ""],
    ["。", "", "", ""],
    ["带着", "dài zhe", "With", "Dengan"],
    ["刚和同学", "gāng hé tóng xué", "just parted with classmates", "baru berpisah dengan rakan"],
    ["分手后的", "fēn shǒu hòu de", "after", "selepas"],
    ["那一点嚣张", "nà yì diǎn xiāo zhāng", "a bit of arrogance", "sedikit angkuh"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["就在", "jiù zài", "right there", "di situ"],
    ["矮墙外", "ǎi qiáng wài", "outside the low wall", "di luar tembok rendah"],
    ["大声地叫起来", "dà shēng de jiào qǐ lái", "shouted loudly", "berteriak dengan kuat"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["何方人士", "hé fāng rén shì", "Who", "Siapakah"],
    ["，", "", "", ""],
    ["敢动", "gǎn dòng", "dare to touch", "berani sentuh"],
    ["本人的拖鞋", "běn rén de tuō xié", "my slippers", "selipar saya"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["花园里", "huā yuán lǐ", "In the garden", "Di taman"],
    ["没有动静", "méi yǒu dòng jìng", "there was no movement", "tiada pergerakan"],
    ["。", "", "", ""],
    ["再", "zài", "then", "kemudian"],
    ["往", "wǎng", "towards", "ke arah"],
    ["客厅", "kè tīng", "living room", "ruang tamu"],
    ["的方向", "de fāng xiàng", "direction", "arah"],
    ["看过去", "kàn guò qù", "looked", "melihat"],
    ["，", "", "", ""],
    ["外婆", "wài pó", "Grandma", "Nenek"],
    ["正坐", "zhèng zuò", "was sitting", "sedang duduk"],
    ["在", "zài", "at", "di"],
    ["纱门后面", "shā mén hòu miàn", "behind the screen door", "di belakang pintu kasa"],
    ["，", "", "", ""],
    ["一面", "yí miàn", "while", "sambil"],
    ["摇扇子", "yáo shàn zi", "fanning", "mengipas"],
    ["，", "", "", ""],
    ["一面", "yí miàn", "while", "sambil"],
    ["看着", "kàn zhe", "looking at", "memandang"],
    ["我笑呢", "wǒ xiào ne", "me smiling", "saya tersenyum"],
    ["。", "", "", ""],
    ["那时", "nà shí", "At that time", "Pada masa itu"],
    ["外婆", "wài pó", "Grandma", "Nenek"],
    ["住在", "zhù zài", "lived in", "tinggal di"],
    ["永和", "yǒng hé", "Yonghe", "Yonghe"],
    ["，", "", "", ""],
    ["很少", "hěn shǎo", "rarely", "jarang"],
    ["上山来", "shàng shān lái", "came up the mountain", "datang ke gunung"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["来的话", "lái de huà", "if she came", "jika datang"],
    ["就总会", "jiù zǒng huì", "would always", "pasti akan"],
    ["住上", "zhù shàng", "stay for", "tinggal selama"],
    ["一两天", "yì liǎng tiān", "a day or two", "satu dua hari"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["我们", "wǒ men", "us", "kami"],
    ["好好地", "hǎo hǎo de", "properly", "dengan baik"],
    ["宠上", "chǒng shàng", "pamper", "memanjakan"],
    ["一阵子", "yí zhèn zi", "for a while", "seketika"],
    ["再走", "zài zǒu", "before leaving", "sebelum pergi"],
    ["。", "", "", ""],
    ["那天傍晚", "nà tiān bàng wǎn", "That evening", "Petang itu"],
    ["，", "", "", ""],
    ["她就是", "tā jiù shì", "she was", "dia"],
    ["那样含笑地", "nà yàng hán xiào de", "smilingly", "sambil tersenyum"],
    ["对我", "duì wǒ", "to me", "kepada saya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["今天下午", "jīn tiān xià wǔ", "This afternoon", "Petang ini"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["用你们", "yòng nǐ men", "used your", "menggunakan"],
    ["浇花的水管", "jiāo huā de shuǐ guǎn", "watering hose", "hos penyiram bunga"],
    ["给你", "gěi nǐ", "to wash your", "untuk"],
    ["把拖鞋洗了", "bǎ tuō xié xǐ le", "slippers", "mencuci selipar awak"],
    ["，", "", "", ""],
    ["刚放在", "gāng fàng zài", "just put", "baru letak di"],
    ["太阳地里", "tài yáng dì lǐ", "in the sun", "tempat matahari"],
    ["晒晒", "shài shai", "to dry", "menjemur"],
    ["就干了", "jiù gàn le", "and they dried", "terus kering"],
    ["。", "", "", ""],
    ["多方便", "duō fāng biàn", "How convenient", "Sungguh mudah"],
    ["！", "", "", ""],
    ["多大的姑娘啦", "duō dà de gū niang la", "Such a big girl", "Gadis sebesar ini"],
    ["！", "", "", ""],
    ["穿这么脏的鞋", "chuān zhè me zāng de xié", "wearing such dirty shoes", "pakai kasut begini kotor"],
    ["给人笑话", "gěi rén xiào hua", "for others to laugh at", "untuk orang ketawakan"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["以后", "yǐ hòu", "After that", "Selepas itu"],
    ["，", "", "", ""],
    ["外婆", "wài pó", "Grandma", "Nenek"],
    ["每次上山时", "měi cì shàng shān shí", "every time she came up the mountain", "setiap kali dia datang ke gunung"],
    ["，", "", "", ""],
    ["总会", "zǒng huì", "would always", "pasti akan"],
    ["替我把拖鞋洗干净", "tì wǒ bǎ tuō xié xǐ gān jìng", "wash my slippers", "mencuci selipar saya"],
    ["，", "", "", ""],
    ["晒好", "shài hǎo", "dry them", "menjemur"],
    ["，", "", "", ""],
    ["有时甚至", "yǒu shí shèn zhì", "sometimes even", "kadang-kadang malah"],
    ["给我", "gěi wǒ", "put them for me", "letakkan untuk saya"],
    ["放到床前", "fàng dào chuáng qián", "in front of the bed", "di hadapan katil"],
    ["。", "", "", ""],
    ["然后", "rán hòu", "Then", "Kemudian"],
    ["在", "zài", "in", "pada"],
    ["傍晚时分", "bàng wǎn shí fēn", "in the evening", "waktu petang"],
    ["，", "", "", ""],
    ["她就会", "tā jiù huì", "she would", "dia akan"],
    ["安详地", "ān xiáng de", "serenely", "dengan tenang"],
    ["坐在客厅里", "zuò zài kè tīng lǐ", "sit in the living room", "duduk di ruang tamu"],
    ["，", "", "", ""],
    ["一面摇扇子", "yí miàn yáo shàn zi", "fanning", "sambil mengipas"],
    ["，", "", "", ""],
    ["一面等着我们回来", "yí miàn děng zhe wǒ men huí lái", "waiting for us to come home", "sambil menunggu kami pulang"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["常常会", "cháng cháng huì", "often would", "sering akan"],
    ["在", "zài", "when", "apabila"],
    ["穿上拖鞋时", "chuān shàng tuō xié shí", "putting on the slippers", "memakai selipar"],
    ["，", "", "", ""],
    ["觉得", "jué de", "feel", "merasa"],
    ["有一股", "yǒu yì gǔ", "there was a", "ada satu"],
    ["暖和与舒适的感觉", "nuǎn huo yǔ shū shì de gǎn jué", "warm and comfortable feeling", "perasaan hangat dan selesa"],
    ["，", "", "", ""],
    ["不知道", "bù zhī dào", "not knowing", "tidak tahu"],
    ["是", "shì", "whether it was", "adakah"],
    ["院子里", "yuàn zi lǐ", "in the yard", "di halaman"],
    ["下午的太阳", "xià wǔ de tài yáng", "the afternoon sun", "matahari petang"],
    ["呢", "ne", "", ""],
    ["，", "", "", ""],
    ["还是", "hái shì", "or", "atau"],
    ["外婆手上的余温", "wài pó shǒu shàng de yú wēn", "the remaining warmth from Grandma's hands", "panas yang tinggal dari tangan nenek"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["就是", "jiù shì", "It is precisely", "Ialah"],
    ["因为", "yīn wèi", "because of", "kerana"],
    ["舍不得", "shě bu de", "couldn't bear to part with", "sayang"],
    ["这一点余温", "zhè yì diǎn yú wēn", "this trace of warmth", "sedikit kehangatan ini"],
    ["，", "", "", ""],
    ["外婆去世的", "wài pó qù shì de", "When Grandma passed away", "Selepas nenek meninggal"],
    ["消息传来以后", "xiāo xī chuán lái yǐ hòu", "the news came", "berita datang"],
    ["，", "", "", ""],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["能够", "néng gòu", "could", "boleh"],
    ["让我纪念她老人家的", "ràng wǒ jì niàn tā lǎo rén jiā de", "things that let me remember her", "yang membolehkan saya mengingatinya"],
    ["东西", "dōng xi", "things", "benda"],
    ["：", "", "", ""],
    ["比如", "bǐ rú", "such as", "contohnya"],
    ["出国前夕", "chū guó qián xī", "before going abroad", "sebelum ke luar negara"],
    ["给我的戒指", "gěi wǒ de jiè zhǐ", "the ring she gave me", "cincin yang diberi"],
    ["，", "", "", ""],
    ["给我买料子", "gěi wǒ mǎi liào zi", "buying fabric for me", "membeli kain untuk saya"],
    ["赶做的小棉袄", "gǎn zuò de xiǎo mián ǎo", "the cotton jacket she hurriedly made", "jaket kapas yang dibuat dengan tergesa-gesa"],
    ["，", "", "", ""],
    ["都在", "dōu zài", "were all", "semuanya"],
    ["泪眼盈盈中", "lèi yǎn yíng yíng zhōng", "with tearful eyes", "dengan mata berair"],
    ["好好地收起来了", "hǎo hǎo de shōu qǐ lái le", "carefully put away", "disimpan dengan baik"],
    ["。", "", "", ""],
    ["这双拖鞋", "zhè shuāng tuō xié", "These slippers", "Selipar ini"],
    ["，", "", "", ""],
    ["也就", "yě jiù", "also", "juga"],
    ["一直", "yì zhí", "always", "sentiasa"],
    ["留在身边", "liú zài shēn biān", "kept with me", "tinggal di sisi"],
    ["，", "", "", ""],
    ["舍不得丢", "shě bu de diū", "couldn't bear to throw away", "sayang nak buang"],
    ["。", "", "", ""],
    ["每次", "měi cì", "Every time", "Setiap kali"],
    ["接触到", "jiē chù dào", "touching", "menyentuh"],
    ["它灰旧的表面", "tā huī jiù de biǎo miàn", "its grey and worn surface", "permukaannya yang kelabu dan lama"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["也", "yě", "also", "juga"],
    ["接触到", "jiē chù dào", "touching", "menyentuh"],
    ["曾洗过它的", "céng xǐ guò tā de", "who had washed them", "yang pernah mencucinya"],
    ["外婆的", "wài pó de", "Grandma's", "nenek punya"],
    ["温暖而多皱的手", "wēn nuǎn ér duō zhòu de shǒu", "warm and wrinkled hands", "tangan yang hangat dan berkedut"],
    ["，", "", "", ""],
    ["便会想起", "biàn huì xiǎng qǐ", "would remember", "akan teringat"],
    ["那在夕阳下的", "nà zài xī yáng xià de", "in the sunset", "di bawah senja"],
    ["园中小径", "yuán zhōng xiǎo jìng", "garden path", "lorong taman"],
    ["，", "", "", ""],
    ["和", "hé", "and", "dan"],
    ["外婆在客厅", "wài pó zài kè tīng", "Grandma in the living room", "nenek di ruang tamu"],
    ["纱门后面的笑容", "shā mén hòu miàn de xiào róng", "smile behind the screen door", "senyuman di belakang pintu kasa"],
    ["。", "", "", ""],
    ["那么遥远", "nà me yáo yuǎn", "So far away", "Begitu jauh"],
    ["，", "", "", ""],
    ["那么温柔", "nà me wēn róu", "so gentle", "begitu lembut"],
    ["，", "", "", ""],
    ["而又", "ér yòu", "and yet", "dan"],
    ["那么肯定地", "nà me kěn dìng de", "so surely", "begitu pasti"],
    ["一去不返", "yí qù bù fǎn", "gone forever", "pergi tidak kembali"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", "", ""],
    ["席慕蓉", "xí mù róng", "Xi Murong", "Xi Murong", "席慕蓉"],
    ["《", "", "", "", ""],
    ["无边的回忆", "wú biān de huí yì", "Endless Memories", "Kenangan Tanpa Sempadan", "无边的回忆"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
