// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "无边的回忆";

const lessonData = [
    // ===== 第1段 =====
    ["我", "wǒ", "I", "Saya"],
    ["有", "yǒu", "have", "ada"],
    ["一双", "yī shuāng", "a pair", "sepasang"],
    ["塑料", "sù liào", "plastic", "plastik"],
    ["的", "de", "", ""],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["，", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["在", "zài", "at", "pada"],
    ["出国", "chū guó", "go abroad", "keluar negara"],
    ["前", "qián", "before", "sebelum"],
    ["两年", "liǎng nián", "two years", "dua tahun"],
    ["买", "mǎi", "bought", "beli"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["出国", "chū guó", "go abroad", "keluar negara"],
    ["后", "hòu", "after", "selepas"],
    ["又", "yòu", "again", "lagi"],
    ["穿", "chuān", "worn", "pakai"],
    ["了", "le", "", ""],
    ["五年", "wǔ nián", "five years", "lima tahun"],
    ["。", "", "", ""],
    ["它", "tā", "its", "ia"],
    ["的", "de", "", ""],
    ["形状", "xíng zhuàng", "shape", "bentuk"],
    ["很", "hěn", "very", "sangat"],
    ["普通", "pǔ tōng", "ordinary", "biasa"],
    ["，", "", "", ""],
    ["就", "jiù", "just", "seperti"],
    ["像", "xiàng", "like", "seperti"],
    ["你", "nǐ", "you", "awak"],
    ["在", "zài", "in", "di"],
    ["台北", "tái běi", "Taipei", "Taipei"],
    ["街头", "jiē tóu", "street", "jalanan"],
    ["随处", "suí chù", "anywhere", "di mana-mana"],
    ["可见", "kě jiàn", "can be seen", "boleh dilihat"],
    ["的", "de", "", ""],
    ["最", "zuì", "most", "paling"],
    ["平常", "píng cháng", "common", "biasa"],
    ["的", "de", "", ""],
    ["样式", "yàng shì", "style", "gaya"],
    ["：", "", "", ""],
    ["平底", "píng dǐ", "flat sole", "tapak rata"],
    ["，", "", "", ""],
    ["浅蓝色", "qiǎn lán sè", "light blue", "biru muda"],
    ["，", "", "", ""],
    ["前端", "qián duān", "front", "hujung depan"],
    ["镂空", "lòu kōng", "hollowed out", "berlubang"],
    ["成", "chéng", "into", "menjadi"],
    ["六条", "liù tiáo", "six", "enam"],
    ["圆带子", "yuán dài zi", "round straps", "tali bulat"],
    ["，", "", "", ""],
    ["中间", "zhōng jiān", "middle", "tengah"],
    ["用", "yòng", "use", "menggunakan"],
    ["上", "shàng", "up", "atas"],
    ["一个", "yī gè", "a", "satu"],
    ["结", "jié", "knot", "simpulan"],
    ["把", "bǎ", "", ""],
    ["它们", "tā men", "them", "mereka"],
    ["连", "lián", "connect", "menyambung"],
    ["起来", "qǐ lái", "up", "naik"],
    ["。", "", "", ""],
    ["买", "mǎi", "buy", "beli"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "apabila"],
    ["是", "shì", "is", "ialah"],
    ["喜欢", "xǐ huān", "like", "suka"],
    ["它", "tā", "its", "ia"],
    ["的", "de", "", ""],
    ["颜色", "yán sè", "color", "warna"],
    ["。", "", "", ""],
    ["穿", "chuān", "worn", "pakai"],
    ["了", "le", "", ""],
    ["五六年", "wǔ liù nián", "five or six years", "lima enam tahun"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["由", "yóu", "from", "dari"],
    ["浅蓝", "qiǎn lán", "light blue", "biru muda"],
    ["变成", "biàn chéng", "become", "menjadi"],
    ["浅灰", "qiǎn huī", "light gray", "kelabu muda"],
    ["，", "", "", ""],
    ["鞋底", "xié dǐ", "sole", "tapak kasut"],
    ["也", "yě", "also", "juga"],
    ["磨", "mó", "worn", "haus"],
    ["得", "de", "", ""],
    ["一边", "yī biān", "one side", "satu sisi"],
    ["高", "gāo", "high", "tinggi"],
    ["一边", "yī biān", "one side", "satu sisi"],
    ["低", "dī", "low", "rendah"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["好几次", "hǎo jǐ cì", "several times", "beberapa kali"],
    ["，", "", "", ""],
    ["有", "yǒu", "have", "ada"],
    ["爱管闲事", "ài guǎn xián shì", "meddlesome", "suka menyibuk"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["好心", "hǎo xīn", "kind", "baik hati"],
    ["的", "de", "", ""],
    ["女孩子", "nǚ hái zi", "girls", "budak perempuan"],
    ["劝", "quàn", "advise", "menasihati"],
    ["我", "wǒ", "me", "saya"],
    ["：", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["“", "", "", ""],
    ["阿蓉", "ā róng", "A Rong", "A Rong"],
    ["，", "", "", ""],
    ["你", "nǐ", "your", "awak"],
    ["这双", "zhè shuāng", "this pair", "sepasang ini"],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["太", "tài", "too", "terlalu"],
    ["老爷", "lǎo yé", "old", "tua"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["阿蓉", "ā róng", "A Rong", "A Rong"],
    ["你", "nǐ", "you", "awak"],
    ["该", "gāi", "should", "patut"],
    ["换", "huàn", "change", "tukar"],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["啦", "la", "", ""],
    ["！”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["总是", "zǒng shì", "always", "sentiasa"],
    ["微笑", "wēi xiào", "smile", "senyum"],
    ["地", "de", "", ""],
    ["回答", "huí dá", "answer", "menjawab"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["还可以", "hái kě yǐ", "still can", "masih boleh"],
    ["穿", "chuān", "wear", "pakai"],
    ["嘛", "ma", "", ""],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["很", "hěn", "very", "sangat"],
    ["喜欢", "xǐ huān", "like", "suka"],
    ["它", "tā", "it", "ia"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["如果", "rú guǒ", "if", "jika"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["回答", "huí dá", "answer", "jawapan"],
    ["换来", "huàn lái", "get in return", "mendapat"],
    ["的", "de", "", ""],
    ["是", "shì", "is", "ialah"],
    ["一个", "yī gè", "a", "satu"],
    ["很", "hěn", "very", "sangat"],
    ["不以为然", "bù yǐ wéi rán", "disapproving", "tidak bersetuju"],
    ["的", "de", "", ""],
    ["表情", "biǎo qíng", "expression", "ekspresi"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["就", "jiù", "then", "lalu"],
    ["会", "huì", "will", "akan"],
    ["设法", "shè fǎ", "try", "cuba"],
    ["转变", "zhuǎn biàn", "change", "tukar"],
    ["一个", "yī gè", "a", "satu"],
    ["话题", "huà tí", "topic", "topik"],
    ["。", "", "", ""],
    ["如果", "rú guǒ", "if", "jika"],
    ["对方", "duì fāng", "the other party", "pihak lain"],
    ["还", "hái", "still", "masih"],
    ["会", "huì", "will", "akan"],
    ["对", "duì", "to", "terhadap"],
    ["我", "wǒ", "me", "saya"],
    ["善意", "shàn yì", "kindly", "dengan baik"],
    ["地", "de", "", ""],
    ["摇摇头", "yáo yáo tóu", "shake head", "menggeleng kepala"],
    ["，", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["笑一笑", "xiào yī xiào", "smile", "tersenyum"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["就", "jiù", "then", "lalu"],
    ["会", "huì", "will", "akan"],
    ["忍不住", "rěn bù zhù", "cannot help", "tidak dapat menahan"],
    ["要", "yào", "want", "mahu"],
    ["告诉", "gào su", "tell", "memberitahu"],
    ["她", "tā", "her", "dia"],
    ["：", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["知道", "zhī dào", "know", "tahu"],
    ["我", "wǒ", "I", "saya"],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["舍不得", "shě bù dé", "cannot bear to", "tidak sanggup"],
    ["丢", "diū", "throw away", "buang"],
    ["它", "tā", "it", "ia"],
    ["的", "de", "", ""],
    ["原因", "yuán yīn", "reason", "sebab"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["而", "ér", "And", "Dan"],
    ["这", "zhè", "this", "ini"],
    ["是", "shì", "is", "ialah"],
    ["个", "gè", "", ""],
    ["让", "ràng", "let", "membuat"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["在", "zài", "in", "pada"],
    ["刹那间", "chà nà jiān", "instant", "sekelip mata"],
    ["变得", "biàn de", "become", "menjadi"],
    ["非常", "fēi cháng", "very", "sangat"],
    ["温柔", "wēn róu", "gentle", "lembut"],
    ["的", "de", "", ""],
    ["回忆", "huí yì", "memory", "kenangan"],
    ["。", "", "", ""],
    ["大学", "dà xué", "university", "universiti"],
    ["快", "kuài", "soon", "hampir"],
    ["毕业", "bì yè", "graduate", "graduasi"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["课", "kè", "classes", "kelas"],
    ["比较", "bǐ jiào", "relatively", "agak"],
    ["少", "shǎo", "few", "sedikit"],
    ["，", "", "", ""],
    ["家", "jiā", "home", "rumah"],
    ["住在", "zhù zài", "live in", "tinggal di"],
    ["北投", "běi tóu", "Beitou", "Beitou"],
    ["山上", "shān shàng", "on the mountain", "di atas gunung"],
    ["，", "", "", ""],
    ["没有", "méi yǒu", "no", "tiada"],
    ["课", "kè", "class", "kelas"],
    ["的", "de", "", ""],
    ["早上", "zǎo shang", "morning", "pagi"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["常常", "cháng cháng", "often", "selalu"],
    ["会", "huì", "will", "akan"],
    ["带着", "dài zhe", "bring", "membawa"],
    ["两只", "liǎng zhī", "two", "dua"],
    ["小狗", "xiǎo gǒu", "puppies", "anak anjing"],
    ["满山", "mǎn shān", "all over the mountain", "seluruh gunung"],
    ["乱跑", "luàn pǎo", "run around", "berlari-lari"],
    ["。", "", "", ""],
    ["有", "yǒu", "have", "ada"],
    ["太阳", "tài yáng", "sun", "matahari"],
    ["的", "de", "", ""],
    ["日子", "rì zi", "days", "hari"],
    ["，", "", "", ""],
    ["大屯山", "dà tún shān", "Datun Mountain", "Gunung Datun"],
    ["腰", "yāo", "waist", "pinggang"],
    ["上", "shàng", "on", "atas"],
    ["的", "de", "", ""],
    ["美丽", "měi lì", "beauty", "keindahan"],
    ["简直", "jiǎn zhí", "simply", "sungguh"],
    ["无法形容", "wú fǎ xíng róng", "indescribable", "tidak dapat digambarkan"],
    ["。", "", "", ""],
    ["有时候", "yǒu shí hou", "sometimes", "kadang-kadang"],
    ["我", "wǒ", "I", "Saya"],
    ["可以", "kě yǐ", "can", "boleh"],
    ["一直", "yī zhí", "always", "terus"],
    ["走", "zǒu", "walk", "berjalan"],
    ["下去", "xià qù", "down", "turun"],
    ["，", "", "", ""],
    ["走", "zǒu", "walk", "berjalan"],
    ["上", "shàng", "up", "atas"],
    ["一两个", "yī liǎng gè", "one or two", "satu dua"],
    ["钟头", "zhōng tóu", "hours", "jam"],
    ["的", "de", "", ""],
    ["路", "lù", "road", "jalan"],
    ["，", "", "", ""],
    ["最", "zuì", "most", "paling"],
    ["让", "ràng", "let", "membuat"],
    ["我", "wǒ", "me", "saya"],
    ["快乐", "kuài lè", "happy", "gembira"],
    ["的", "de", "", ""],
    ["是", "shì", "is", "ialah"],
    ["在", "zài", "in", "di"],
    ["行走", "xíng zǒu", "walking", "berjalan"],
    ["中", "zhōng", "in", "dalam"],
    ["猛然", "měng rán", "suddenly", "tiba-tiba"],
    ["回过头", "huí guò tóu", "turn head", "menoleh"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["再", "zài", "again", "lagi"],
    ["仔细", "zǐ xì", "carefully", "teliti"],
    ["辨认", "biàn rèn", "identify", "mengenal pasti"],
    ["，", "", "", ""],
    ["山坡", "shān pō", "hillside", "cerun bukit"],
    ["下面", "xià miàn", "below", "bawah"],
    ["，", "", "", ""],
    ["哪一幢", "nǎ yī zhuàng", "which building", "bangunan mana"],
    ["是", "shì", "is", "ialah"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["家", "jiā", "home", "rumah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["走着", "zǒu zhe", "walking", "berjalan"],
    ["走着", "zǒu zhe", "walking", "berjalan"],
    ["，", "", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["新", "xīn", "new", "baru"],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["就", "jiù", "then", "lalu"],
    ["不像样", "bù xiàng yàng", "shabby", "tidak nampak elok"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["不过", "bù guò", "however", "bagaimanapun"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["没时间", "méi shí jiān", "no time", "tiada masa"],
    ["管", "guǎn", "care", "peduli"],
    ["它", "tā", "it", "ia"],
    ["，", "", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["下午", "xià wǔ", "afternoon", "petang"],
    ["都是", "dōu shì", "are all", "semuanya"],
    ["排得", "pái de", "scheduled", "dijadualkan"],
    ["满满", "mǎn mǎn", "full", "penuh"],
    ["，", "", "", ""],
    ["别", "bié", "other", "lain"],
    ["有用处", "yǒu yòng chù", "useful", "berguna"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["晚上", "wǎn shàng", "evening", "malam"],
    ["回家", "huí jiā", "return home", "pulang"],
    ["后", "hòu", "after", "selepas"],
    ["赶快", "gǎn kuài", "quickly", "cepat"],
    ["洗", "xǐ", "wash", "cuci"],
    ["个", "gè", "", ""],
    ["澡", "zǎo", "bath", "mandi"],
    ["就", "jiù", "then", "lalu"],
    ["睡", "shuì", "sleep", "tidur"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["一天", "yī tiān", "one day", "satu hari"],
    ["傍晚", "bàng wǎn", "evening", "waktu senja"],
    ["，", "", "", ""],
    ["放学", "fàng xué", "school ends", "tamat sekolah"],
    ["回家", "huí jiā", "return home", "pulang"],
    ["，", "", "", ""],
    ["隔着", "gé zhe", "across", "melalui"],
    ["矮矮", "ǎi ǎi", "low", "rendah"],
    ["的", "de", "", ""],
    ["石墙", "shí qiáng", "stone wall", "dinding batu"],
    ["，", "", "", ""],
    ["看见", "kàn jiàn", "see", "melihat"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["被", "bèi", "by", "oleh"],
    ["整整齐齐", "zhěng zhěng qí qí", "neatly", "tersusun rapi"],
    ["地", "de", "", ""],
    ["摆在", "bǎi zài", "placed at", "diletakkan di"],
    ["花园", "huā yuán", "garden", "taman"],
    ["里", "lǐ", "in", "di"],
    ["的", "de", "", ""],
    ["水泥", "shuǐ ní", "cement", "simen"],
    ["小路", "xiǎo lù", "path", "lorong"],
    ["上", "shàng", "on", "atas"],
    ["。", "", "", ""],
    ["带着", "dài zhe", "with", "dengan"],
    ["刚", "gāng", "just", "baru"],
    ["和", "hé", "and", "dan"],
    ["同学", "tóng xué", "classmates", "rakan sekelas"],
    ["分手", "fēn shǒu", "parted", "berpisah"],
    ["后", "hòu", "after", "selepas"],
    ["的", "de", "", ""],
    ["那一点", "nà yī diǎn", "that bit of", "sedikit itu"],
    ["嚣张", "xiāo zhāng", "arrogance", "sombong"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["就", "jiù", "then", "lalu"],
    ["在", "zài", "at", "di"],
    ["矮墙", "ǎi qiáng", "low wall", "dinding rendah"],
    ["外", "wài", "outside", "luar"],
    ["大声", "dà shēng", "loudly", "kuat"],
    ["地", "de", "", ""],
    ["叫", "jiào", "shout", "jerit"],
    ["起来", "qǐ lái", "up", "naik"],
    ["：", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["“", "", "", ""],
    ["何方", "hé fāng", "where", "di mana"],
    ["人士", "rén shì", "person", "orang"],
    ["，", "", "", ""],
    ["敢", "gǎn", "dare", "berani"],
    ["动", "dòng", "touch", "sentuh"],
    ["本人", "běn rén", "my own", "saya sendiri"],
    ["的", "de", "", ""],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["花园", "huā yuán", "garden", "taman"],
    ["里", "lǐ", "in", "di"],
    ["没有", "méi yǒu", "no", "tiada"],
    ["动静", "dòng jìng", "movement", "pergerakan"],
    ["。", "", "", ""],
    ["再", "zài", "then", "kemudian"],
    ["往", "wǎng", "towards", "ke"],
    ["客厅", "kè tīng", "living room", "ruang tamu"],
    ["的", "de", "", ""],
    ["方向", "fāng xiàng", "direction", "arah"],
    ["看过去", "kàn guò qù", "look over", "melihat ke"],
    ["，", "", "", ""],
    ["外婆", "wài pó", "grandmother", "nenek"],
    ["正", "zhèng", "is", "sedang"],
    ["坐在", "zuò zài", "sitting at", "duduk di"],
    ["纱门", "shā mén", "screen door", "pintu skrin"],
    ["后面", "hòu miàn", "behind", "belakang"],
    ["，", "", "", ""],
    ["一面", "yī miàn", "one side", "sambil"],
    ["摇", "yáo", "fan", "kibas"],
    ["扇子", "shàn zi", "fan", "kipas"],
    ["，", "", "", ""],
    ["一面", "yī miàn", "one side", "sambil"],
    ["看着", "kàn zhe", "looking at", "melihat"],
    ["我", "wǒ", "me", "saya"],
    ["笑", "xiào", "smile", "senyum"],
    ["呢", "ne", "", ""],
    ["。", "", "", ""],
    ["那时", "nà shí", "at that time", "pada masa itu"],
    ["外婆", "wài pó", "grandmother", "nenek"],
    ["住在", "zhù zài", "live in", "tinggal di"],
    ["永和", "yǒng hé", "Yonghe", "Yonghe"],
    ["，", "", "", ""],
    ["很少", "hěn shǎo", "rarely", "jarang"],
    ["上山", "shàng shān", "go up the mountain", "naik gunung"],
    ["来", "lái", "come", "datang"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["来", "lái", "come", "datang"],
    ["的话", "de huà", "if", "jika"],
    ["就", "jiù", "then", "lalu"],
    ["总会", "zǒng huì", "always will", "sentiasa akan"],
    ["住上", "zhù shàng", "stay", "tinggal"],
    ["一两天", "yī liǎng tiān", "one or two days", "satu dua hari"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["我们", "wǒ men", "us", "kita"],
    ["好好", "hǎo hǎo", "well", "dengan baik"],
    ["地", "de", "", ""],
    ["宠", "chǒng", "dote on", "manjakan"],
    ["上", "shàng", "up", "atas"],
    ["一阵子", "yī zhèn zi", "a while", "seketika"],
    ["再", "zài", "then", "kemudian"],
    ["走", "zǒu", "go", "pergi"],
    ["。", "", "", ""],
    ["那天", "nà tiān", "that day", "hari itu"],
    ["傍晚", "bàng wǎn", "evening", "waktu senja"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["就是", "jiù shì", "just", "iaitu"],
    ["那样", "nà yàng", "like that", "begitu"],
    ["含笑", "hán xiào", "smiling", "tersenyum"],
    ["地", "de", "", ""],
    ["对", "duì", "to", "kepada"],
    ["我", "wǒ", "me", "saya"],
    ["说", "shuō", "say", "berkata"],
    ["：", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["“", "", "", ""],
    ["今天", "jīn tiān", "today", "hari ini"],
    ["下午", "xià wǔ", "afternoon", "petang"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["用", "yòng", "use", "menggunakan"],
    ["你们", "nǐ men", "your", "kamu"],
    ["浇花", "jiāo huā", "water flowers", "menyiram bunga"],
    ["的", "de", "", ""],
    ["水管", "shuǐ guǎn", "hose", "paip air"],
    ["给", "gěi", "for", "untuk"],
    ["你", "nǐ", "you", "awak"],
    ["把", "bǎ", "", ""],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["洗", "xǐ", "washed", "cuci"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["刚", "gāng", "just", "baru"],
    ["放在", "fàng zài", "placed at", "diletakkan di"],
    ["太阳地", "tài yáng dì", "sunny place", "tempat panas"],
    ["里", "lǐ", "in", "di"],
    ["晒晒", "shài shài", "dry in the sun", "jemur"],
    ["就", "jiù", "then", "lalu"],
    ["干", "gān", "dry", "kering"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["多", "duō", "how", "betapa"],
    ["方便", "fāng biàn", "convenient", "senang"],
    ["！", "", "", ""],
    ["多大", "duō dà", "how old", "berapa besar"],
    ["的", "de", "", ""],
    ["姑娘", "gū niáng", "girl", "gadis"],
    ["啦", "la", "", ""],
    ["！", "", "", ""],
    ["穿", "chuān", "wear", "pakai"],
    ["这么", "zhè me", "so", "begitu"],
    ["脏", "zāng", "dirty", "kotor"],
    ["的", "de", "", ""],
    ["鞋", "xié", "shoes", "kasut"],
    ["给", "gěi", "let", "biar"],
    ["人", "rén", "people", "orang"],
    ["笑话", "xiào huà", "laugh at", "ketawakan"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["以后", "yǐ hòu", "afterwards", "selepas itu"],
    ["，", "", "", ""],
    ["外婆", "wài pó", "grandmother", "nenek"],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["上山", "shàng shān", "go up the mountain", "naik gunung"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["总会", "zǒng huì", "always will", "sentiasa akan"],
    ["替", "tì", "for", "untuk"],
    ["我", "wǒ", "me", "saya"],
    ["把", "bǎ", "", ""],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["洗", "xǐ", "wash", "cuci"],
    ["干净", "gān jìng", "clean", "bersih"],
    ["，", "", "", ""],
    ["晒好", "shài hǎo", "dry", "jemur"],
    ["，", "", "", ""],
    ["有时", "yǒu shí", "sometimes", "kadang-kadang"],
    ["甚至", "shèn zhì", "even", "malah"],
    ["给", "gěi", "for", "untuk"],
    ["我", "wǒ", "me", "saya"],
    ["放到", "fàng dào", "put at", "letak di"],
    ["床前", "chuáng qián", "bedside", "sisi katil"],
    ["。", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["在", "zài", "in", "pada"],
    ["傍晚", "bàng wǎn", "evening", "waktu senja"],
    ["时分", "shí fēn", "time", "waktu"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["就", "jiù", "then", "lalu"],
    ["会", "huì", "will", "akan"],
    ["安详", "ān xiáng", "serenely", "dengan tenang"],
    ["地", "de", "", ""],
    ["坐在", "zuò zài", "sit at", "duduk di"],
    ["客厅", "kè tīng", "living room", "ruang tamu"],
    ["里", "lǐ", "in", "di"],
    ["，", "", "", ""],
    ["一面", "yī miàn", "one side", "sambil"],
    ["摇", "yáo", "fan", "kibas"],
    ["扇子", "shàn zi", "fan", "kipas"],
    ["，", "", "", ""],
    ["一面", "yī miàn", "one side", "sambil"],
    ["等着", "děng zhe", "waiting", "menunggu"],
    ["我们", "wǒ men", "us", "kita"],
    ["回来", "huí lái", "return", "pulang"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["常常", "cháng cháng", "often", "selalu"],
    ["会", "huì", "will", "akan"],
    ["在", "zài", "when", "apabila"],
    ["穿上", "chuān shàng", "put on", "memakai"],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["觉得", "jué de", "feel", "rasa"],
    ["有", "yǒu", "have", "ada"],
    ["一股", "yī gǔ", "a", "satu"],
    ["暖和", "nuǎn huo", "warm", "hangat"],
    ["与", "yǔ", "and", "dan"],
    ["舒适", "shū shì", "comfortable", "selesa"],
    ["的", "de", "", ""],
    ["感觉", "gǎn jué", "feeling", "perasaan"],
    ["，", "", "", ""],
    ["不知道", "bù zhī dào", "don't know", "tidak tahu"],
    ["是", "shì", "is", "ialah"],
    ["院子", "yuàn zi", "courtyard", "halaman"],
    ["里", "lǐ", "in", "di"],
    ["下午", "xià wǔ", "afternoon", "petang"],
    ["的", "de", "", ""],
    ["太阳", "tài yáng", "sun", "matahari"],
    ["呢", "ne", "", ""],
    ["，", "", "", ""],
    ["还是", "hái shì", "or", "atau"],
    ["外婆", "wài pó", "grandmother", "nenek"],
    ["手上", "shǒu shàng", "hands", "tangan"],
    ["的", "de", "", ""],
    ["余温", "yú wēn", "remaining warmth", "kehangatan sisa"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["就是", "jiù shì", "It is", "Ia adalah"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["舍不得", "shě bù dé", "cannot bear to part with", "tidak sanggup"],
    ["这", "zhè", "this", "ini"],
    ["一点", "yī diǎn", "a bit of", "sedikit"],
    ["余温", "yú wēn", "remaining warmth", "kehangatan sisa"],
    ["，", "", "", ""],
    ["外婆", "wài pó", "grandmother", "nenek"],
    ["去世", "qù shì", "passed away", "meninggal dunia"],
    ["的", "de", "", ""],
    ["消息", "xiāo xi", "news", "berita"],
    ["传来", "chuán lái", "came", "datang"],
    ["以后", "yǐ hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["能够", "néng gòu", "can", "boleh"],
    ["让", "ràng", "let", "membuat"],
    ["我", "wǒ", "me", "saya"],
    ["纪念", "jì niàn", "commemorate", "mengenang"],
    ["她", "tā", "her", "dia"],
    ["老人家", "lǎo rén jiā", "elderly person", "orang tua"],
    ["的", "de", "", ""],
    ["东西", "dōng xi", "things", "benda"],
    ["：", "", "", ""],
    ["比如", "bǐ rú", "for example", "contohnya"],
    ["出国", "chū guó", "go abroad", "keluar negara"],
    ["前夕", "qián xī", "eve", "malam sebelum"],
    ["给", "gěi", "gave", "memberi"],
    ["我", "wǒ", "me", "saya"],
    ["的", "de", "", ""],
    ["戒指", "jiè zhǐ", "ring", "cincin"],
    ["，", "", "", ""],
    ["给", "gěi", "gave", "memberi"],
    ["我", "wǒ", "me", "saya"],
    ["买", "mǎi", "bought", "beli"],
    ["料子", "liào zi", "fabric", "kain"],
    ["赶做", "gǎn zuò", "hurry to make", "cepat membuat"],
    ["的", "de", "", ""],
    ["小棉袄", "xiǎo mián ǎo", "small cotton jacket", "jaket kapas kecil"],
    ["，", "", "", ""],
    ["都", "dōu", "all", "semua"],
    ["在", "zài", "in", "di"],
    ["泪眼盈盈", "lèi yǎn yíng yíng", "tearful eyes", "mata bergenang air mata"],
    ["中", "zhōng", "in", "dalam"],
    ["好好", "hǎo hǎo", "properly", "dengan baik"],
    ["地", "de", "", ""],
    ["收起", "shōu qǐ", "keep", "simpan"],
    ["来了", "lái le", "up", "naik"],
    ["。", "", "", ""],
    ["这双", "zhè shuāng", "this pair", "sepasang ini"],
    ["拖鞋", "tuō xié", "slippers", "selipar"],
    ["，", "", "", ""],
    ["也就", "yě jiù", "also", "juga"],
    ["一直", "yī zhí", "always", "sentiasa"],
    ["留在", "liú zài", "remain at", "tinggal di"],
    ["身边", "shēn biān", "side", "sisi"],
    ["，", "", "", ""],
    ["舍不得", "shě bù dé", "cannot bear to", "tidak sanggup"],
    ["丢", "diū", "throw away", "buang"],
    ["。", "", "", ""],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["接触", "jiē chù", "touch", "sentuh"],
    ["到", "dào", "to", "ke"],
    ["它", "tā", "its", "ia"],
    ["灰旧", "huī jiù", "worn gray", "kelabu usang"],
    ["的", "de", "", ""],
    ["表面", "biǎo miàn", "surface", "permukaan"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["也", "yě", "also", "juga"],
    ["接触", "jiē chù", "touch", "sentuh"],
    ["到", "dào", "to", "ke"],
    ["曾", "céng", "once", "pernah"],
    ["洗过", "xǐ guò", "washed", "pernah mencuci"],
    ["它", "tā", "it", "ia"],
    ["的", "de", "", ""],
    ["外婆", "wài pó", "grandmother", "nenek"],
    ["的", "de", "", ""],
    ["温暖", "wēn nuǎn", "warm", "hangat"],
    ["而", "ér", "and", "dan"],
    ["多皱", "duō zhòu", "wrinkled", "berkedut"],
    ["的", "de", "", ""],
    ["手", "shǒu", "hand", "tangan"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["会", "huì", "will", "akan"],
    ["想起", "xiǎng qǐ", "think of", "teringat"],
    ["那", "nà", "that", "itu"],
    ["在", "zài", "in", "di"],
    ["夕阳", "xī yáng", "sunset", "matahari terbenam"],
    ["下", "xià", "under", "bawah"],
    ["的", "de", "", ""],
    ["园中", "yuán zhōng", "in the garden", "di taman"],
    ["小径", "xiǎo jìng", "path", "lorong kecil"],
    ["，", "", "", ""],
    ["和", "hé", "and", "dan"],
    ["外婆", "wài pó", "grandmother", "nenek"],
    ["在", "zài", "in", "di"],
    ["客厅", "kè tīng", "living room", "ruang tamu"],
    ["纱门", "shā mén", "screen door", "pintu skrin"],
    ["后面", "hòu miàn", "behind", "belakang"],
    ["的", "de", "", ""],
    ["笑容", "xiào róng", "smile", "senyuman"],
    ["。", "", "", ""],
    ["那么", "nà me", "so", "begitu"],
    ["遥远", "yáo yuǎn", "distant", "jauh"],
    ["，", "", "", ""],
    ["那么", "nà me", "so", "begitu"],
    ["温柔", "wēn róu", "gentle", "lembut"],
    ["，", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["又", "yòu", "yet", "namun"],
    ["那么", "nà me", "so", "begitu"],
    ["肯定", "kěn dìng", "certain", "pasti"],
    ["地", "de", "", ""],
    ["一去不返", "yī qù bù fǎn", "gone forever", "hilang selama-lamanya"],
    ["。", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
